<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <EnableNETAnalyzers>false</EnableNETAnalyzers>
        <NoWarn>$(NoWarn);1591;S125;S1104;S3604;S3878;S3887;S2386;S2223;S3903;S1871;S3626;S1125;S927;S1643;S1444;S1481;S2325;S2933;S3923;S3400;S2696;S1185;CA1707;CA1051;CA1822;CA1805;CA1708;MSB3277</NoWarn>
        <TargetFramework>net6.0</TargetFramework>
        <DebugType>embedded</DebugType>

        <VersionPrefix>0.1</VersionPrefix>
        <VersionSuffix>v</VersionSuffix>
        <RootNamespace>JAM</RootNamespace>
        <Description>Example mod for Town of Us Mira that shows the basics of adding new roles and modifiers.</Description>
        <!-- <Authors>your name</Authors> -->
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*.*" />
    </ItemGroup>
    
    <ItemGroup>
        <Reference Include="../lib/*.dll">
            <Private>false</Private>
        </Reference>
    </ItemGroup>
    
    <ItemGroup>
      <Compile Remove="Events\Neutral\**" />
      <EmbeddedResource Remove="Events\Neutral\**" />
      <None Remove="Events\Neutral\**" />
      <Reference Remove="Events\Neutral\**" />
    </ItemGroup>

    <ItemGroup>
      <None Include="Assets\JamModifierIcons.cs" />
      <None Include="Options\Roles\Neutral\VacillatorOptions.cs" />
      <None Include="Roles\Impostor\CamouflagerRole.cs" />
      <None Include="Roles\Impostor\DeceiverRole.cs" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Modules\" />
    </ItemGroup>

    <Import Project="../AmongUs.props" />

    <Target Name="Copy" AfterTargets="Build" Condition="'$(AmongUs)' != ''">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(AmongUs)/BepInEx/plugins/" UseSymboliclinksIfPossible="true" />
    </Target>
</Project>
